services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sass_pozstar
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Ensure DATABASE_URL points to the mounted volume location
      - DATABASE_URL=file:/app/prisma/dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      # Mount the prisma directory to persist the database
      - ./prisma:/app/prisma
    env_file:
      - .env
